version: "3.7"

services:
  public-relay:
    image: scsibug/nostr-rs-relay
    restart: on-failure
    volumes:
      - ./data/relay/config.toml:/usr/src/app/config.toml
      - nostrvol:/usr/src/app/db
    container_name: public-relay
    networks:
      - caddy
  web:
    image: getumbrel/umbrel-nostr-relay
    build: .
    user: "1000:1000"
    container_name: public-relay-web
    restart: on-failure
    environment:
      RELAY_HOST: "public-relay"
      RELAY_PORT: "8080"
    networks:
      - caddy
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    networks:
      - caddy
      - default
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data/data:/data
      - ./caddy_data/config:/config
    restart: unless-stopped

networks:
  caddy:
    name: caddy

volumes:
  nostrvol:
    external: true
